import fs from 'fs'
import path from 'path'
import {AfterLoad, Column,Entity,JoinColumn,ManyToOne} from 'typeorm'
import { DotenvConfig } from '../config/env.config'
import {MediaType} from '../constant/enum'
import {getTempFolderPath,getUploadFolderPath} from '../utils/path.utils'
import {AuthDetails} from './auth/details.entity'
import Base from './base.entity'