import {existsSync} from 'fs'
import path from 'path'
import { AppDataSource } from '../config/database.config'
import { Message } from '../constant/messages'
import Media from '../entities/media.entity'
import AppError from '../utils/HttpException'
import {transferImageFromUploadTOTempFolder}from '../utils/media.utils'
import { getTempFolderPath } from '../utils/path.utils'
